// <auto-generated />
namespace CMS.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SplitPropertyandValueAddedlanguagecodetoAlias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SplitPropertyandValueAddedlanguagecodetoAlias));
        
        string IMigrationMetadata.Id
        {
            get { return "201710010942073_Split Property and Value + Added languagecode to Alias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
